chore(deps): bump locust from 1.1 to 1.3.2 in /label_studio/tests/loadtests (#5501)
Bumps [locust](https://github.com/locustio/locust) from 1.1 to 1.3.2.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/locustio/locust/releases">locust's
releases</a>.</em></p>
<blockquote>
<h2>1.3.2</h2>
<ul>
<li>List Python 3.9 as supported in the package/on PyPi</li>
<li>Fix XSS vulnerability in the web UI (sounds important but really
isn't, as Locust UI is not meant to be exposed to outside users)</li>
</ul>
<p>(side note: I have also fixed the docker build process, so any tagged
commit will push to <code>locustio/locust:latest</code>, this was broken
in the past)</p>
<h2>1.3.1</h2>
<ul>
<li>Bump minimum required gevent version to 20.9.0 (latest), as all the
previous ones had sneaky binary incompatibilities with the latest
version of greenlet (&quot;RuntimeWarning: greenlet.greenlet size
changed, may indicate binary incompatibility. Expected 144 from C
header, got 152 from PyObject&quot;)</li>
</ul>
<h2>1.3.0</h2>
<ul>
<li>Breaking change: Remove step-load feature (now that we have
LoadTestShape it is no longer needed)</li>
<li>More type hints to enable better code completion and linting of
locustfiles</li>
<li>Lots of documentation updates</li>
</ul>
<p>Bug fixes:</p>
<ul>
<li>LoadTestShape.get_run_time is not relative to start of test <a
href="https://redirect.github.com/locustio/locust/issues/1557">locustio/locust#1557</a></li>
<li>Refactor and fix delayed user stopping in combination with on_stop
<a
href="https://redirect.github.com/locustio/locust/pull/1560">locustio/locust#1560</a></li>
<li>runner.quit gets blocked by slow on stop <a
href="https://redirect.github.com/locustio/locust/issues/1552">locustio/locust#1552</a></li>
<li>Remove legacy code that was only needed for py2</li>
<li>Lots more (<a
href="https://github.com/locustio/locust/blob/master/CHANGELOG.md">https://github.com/locustio/locust/blob/master/CHANGELOG.md</a>)</li>
</ul>
<h2>1.2.3</h2>
<ul>
<li>Various linting fixes that <em>should</em> have no functional
impact</li>
<li>Bug fix (TypeError: code() takes at least 14 arguments (13 given)
(Werkzeug version issue) <a
href="https://redirect.github.com/locustio/locust/issues/1545">locustio/locust#1545</a>)</li>
<li>Bug fix (Locust stuck in &quot;Shape worker starting&quot; when
restarting a test from the webUI <a
href="https://redirect.github.com/locustio/locust/issues/1540">locustio/locust#1540</a>)</li>
</ul>
<h2>1.2.2</h2>
<ul>
<li>Bug fix (LoadTestShape in headless mode <a
href="https://redirect.github.com/locustio/locust/pull/1539">locustio/locust#1539</a>)</li>
</ul>
<h2>1.2.1</h2>
<ul>
<li>Bug fix (StatsEntry.use_response_times_cache must be set to True, <a
href="https://redirect.github.com/locustio/locust/issues/1531">locustio/locust#1531</a>)</li>
</ul>
<h2>1.2</h2>
<ul>
<li>Rename hatch rate to spawn rate (the –hatch-rate parameter is only
deprecated, but the hatch_complete event has been renamed
spawning_complete)</li>
<li>Ability to generate any custom load shape with LoadTestShape
class</li>
<li>Allow ramping down of users</li>
<li>Ability to use save custom percentiles</li>
<li>Improve command line stats output</li>
<li>Bug fixes (excessive precision of metrics in losust csv stats,
negative response time when system clock has changed, issue with
non-string failure messages, some typos etc)</li>
<li>Documentation improvements</li>
</ul>
<h2>1.1.1</h2>
<ul>
<li>Fix for run not ending if there is an exception in a test_stop
listener</li>
<li>FastHttpUser: Handle stream ended at an unexpected time and
UnicodeDecodeError. Show bad/error status codes on failures page.</li>
<li>Improve logging when locust master port is busy</li>
</ul>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/locustio/locust/blob/master/CHANGELOG.md">locust's
changelog</a>.</em></p>
<blockquote>
<h2><a href="https://github.com/locustio/locust/tree/2.11.1">2.11.1</a>
(2022-08-25)</h2>
<p><a
href="https://github.com/locustio/locust/compare/2.11.0...2.11.1">Full
Changelog</a></p>
<p><strong>Merged pull requests:</strong></p>
<ul>
<li>Use more clear wording in --run-time reached stopping log message.
<a
href="https://redirect.github.com/locustio/locust/pull/2172">#2172</a>
(<a href="https://github.com/cyberw">cyberw</a>)</li>
<li>fix: edit load test missing the userclasses data <a
href="https://redirect.github.com/locustio/locust/pull/2171">#2171</a>
(<a href="https://github.com/alterhu2020">alterhu2020</a>)</li>
<li>Fix custom message example in documentation <a
href="https://redirect.github.com/locustio/locust/pull/2165">#2165</a>
(<a href="https://github.com/aathan">aathan</a>)</li>
<li>Fix broken link in cpu warning message. <a
href="https://redirect.github.com/locustio/locust/pull/2164">#2164</a>
(<a href="https://github.com/conghuiw">conghuiw</a>)</li>
<li>Allow multiple definitions of same user class name if they come from
the same place <a
href="https://redirect.github.com/locustio/locust/pull/2160">#2160</a>
(<a href="https://github.com/cyberw">cyberw</a>)</li>
<li>Include worker_index in worker connection logging, and stop using
the word &quot;client&quot; for what is actually a worker <a
href="https://redirect.github.com/locustio/locust/pull/2159">#2159</a>
(<a href="https://github.com/cyberw">cyberw</a>)</li>
<li>Upgrade GitHub Actions <a
href="https://redirect.github.com/locustio/locust/pull/2158">#2158</a>
(<a href="https://github.com/cclauss">cclauss</a>)</li>
<li>Fix typo <a
href="https://redirect.github.com/locustio/locust/pull/2157">#2157</a>
(<a href="https://github.com/cclauss">cclauss</a>)</li>
</ul>
<h2><a href="https://github.com/locustio/locust/tree/2.11.0">2.11.0</a>
(2022-08-12)</h2>
<p><a
href="https://github.com/locustio/locust/compare/2.10.2...2.11.0">Full
Changelog</a></p>
<p><strong>Fixed bugs:</strong></p>
<ul>
<li>Not able to achieve high RPS (3000 users, 20 workers, 32 vcpu-64 GB
RAM) <a
href="https://redirect.github.com/locustio/locust/issues/2154">#2154</a></li>
<li>Flask 2.2.0 Update breaks request_stats_full_history_csv in web.py
<a
href="https://redirect.github.com/locustio/locust/issues/2147">#2147</a></li>
<li>&quot;New test&quot; with different number of users <a
href="https://redirect.github.com/locustio/locust/issues/2135">#2135</a></li>
</ul>
<p><strong>Closed issues:</strong></p>
<ul>
<li>Use of different LoadTestShape classes in the same locust file <a
href="https://redirect.github.com/locustio/locust/issues/2151">#2151</a></li>
</ul>
<p><strong>Merged pull requests:</strong></p>
<ul>
<li>Add example launch.json for debugging the whole Locust runtime in
vscode <a
href="https://redirect.github.com/locustio/locust/pull/2156">#2156</a>
(<a href="https://github.com/SamPosh">SamPosh</a>)</li>
<li>feat: add 'worker_index' to WorkerRunner <a
href="https://redirect.github.com/locustio/locust/pull/2155">#2155</a>
(<a href="https://github.com/gdm85">gdm85</a>)</li>
<li>chore: Remove misleading docstring in test <a
href="https://redirect.github.com/locustio/locust/pull/2153">#2153</a>
(<a href="https://github.com/mboutet">mboutet</a>)</li>
<li>fix: Ensure new test starts with specified number of users after
previous test has been stopped <a
href="https://redirect.github.com/locustio/locust/pull/2152">#2152</a>
(<a href="https://github.com/mboutet">mboutet</a>)</li>
<li>Pass multiple Locustfiles and allow selecting User and Shape class
from the WebUI <a
href="https://redirect.github.com/locustio/locust/pull/2137">#2137</a>
(<a href="https://github.com/mikenester">mikenester</a>)</li>
</ul>
<h2><a href="https://github.com/locustio/locust/tree/2.10.2">2.10.2</a>
(2022-08-03)</h2>
<p><a
href="https://github.com/locustio/locust/compare/2.10.1...2.10.2">Full
Changelog</a></p>
<p><strong>Fixed bugs:</strong></p>
<ul>
<li>[SocketIOUser] - I have provided the code to turn off the SSL
certification but still, I'm getting an SSL certification error <a
href="https://redirect.github.com/locustio/locust/issues/2144">#2144</a></li>
<li>HTML Report does not correctly escape statistics data <a
href="https://redirect.github.com/locustio/locust/issues/2126">#2126</a></li>
<li>&quot;Stop&quot; hang on &quot;stopping&quot; state when there are
more than one workers in distributed mode. <a
href="https://redirect.github.com/locustio/locust/issues/2111">#2111</a></li>
</ul>
<p><strong>Closed issues:</strong></p>
<ul>
<li>Html report: table should be sortable <a
href="https://redirect.github.com/locustio/locust/issues/2132">#2132</a></li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/locustio/locust/commit/01c0fa4d807f645b8971b56b05e6757f3daddda1"><code>01c0fa4</code></a>
Revert &quot;Add py39 to black config&quot;</li>
<li><a
href="https://github.com/locustio/locust/commit/32cfb8873b7eb65382e4063262b4025d459a2dfc"><code>32cfb88</code></a>
Add py39 to black config</li>
<li><a
href="https://github.com/locustio/locust/commit/d9fea47deb7337c951b07aaa632b3a42dcb174e9"><code>d9fea47</code></a>
1.3.2 version bump &amp; changelog</li>
<li><a
href="https://github.com/locustio/locust/commit/a031f2052ec2db6f5013caa9bbe179815a495372"><code>a031f20</code></a>
Clarify documentation of start()'s user_count parameter</li>
<li><a
href="https://github.com/locustio/locust/commit/7f218963688fd58fd124b4f47854ecb16681fac1"><code>7f21896</code></a>
Merge pull request <a
href="https://redirect.github.com/locustio/locust/issues/1607">#1607</a>
from locustio/support-for-python-3.9</li>
<li><a
href="https://github.com/locustio/locust/commit/5db48f0c7ee2f86a58913a2d2c36df49276a5873"><code>5db48f0</code></a>
Merge pull request <a
href="https://redirect.github.com/locustio/locust/issues/1606">#1606</a>
from max-rocket-internet/add_chart_doc</li>
<li><a
href="https://github.com/locustio/locust/commit/d2dd606df16e450615a836f323cf9604bcf57bc1"><code>d2dd606</code></a>
format link differently</li>
<li><a
href="https://github.com/locustio/locust/commit/98295948bda8cac366ce7c828cffc81f5a609606"><code>9829594</code></a>
Add note and link to k8s Helm chart</li>
<li><a
href="https://github.com/locustio/locust/commit/aa7b34db3a87fa5cd7a2fa9e4030777f8ca2f3a3"><code>aa7b34d</code></a>
Black</li>
<li><a
href="https://github.com/locustio/locust/commit/4049173b3466da236b1d8d8d3519e73c01525a0d"><code>4049173</code></a>
Merge pull request <a
href="https://redirect.github.com/locustio/locust/issues/1603">#1603</a>
from lhupfeldt/host_field_xss</li>
<li>Additional commits viewable in <a
href="https://github.com/locustio/locust/compare/1.1...1.3.2">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=locust&package-manager=pip&previous-version=1.1&new-version=1.3.2)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)
You can disable automated security fix PRs for this repo from the
[Security Alerts
page](https://github.com/HumanSignal/label-studio/network/alerts).

</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>