fix: OPTIC-719: TypeError: e.target.className.includes is not a function (#5847)
Error coming from Sentry 
https://heartex.sentry.io/issues/5039994894/

There is no impact on the user.

This happens when a user drags and drops, for example, when the column
header is an SVG. I confirm that the drag-and-drop feature continues to
work well.

Also, `?` wont work because in the case of failure is an image that is
an svg and className is a `SVGAnimatedString` object. No need to pursue
baseVal since we don't have the className `handle`

---------

Co-authored-by: Raul Martin <raul@humansignal.com>
Co-authored-by: hlomzik <hlomzik@gmail.com>
Co-authored-by: robot-ci-heartex <robot-ci-heartex@users.noreply.github.com>